### ISSUE TITLE
When creating an object it has to be defined

### ISSUE THREAD

**Issue by QuantumCoded** [QuantumCoded/ball-game#1]
In the code I have an object class that is used for things that should be picked up by collision detection.

`function object(properties, css) { ... }`

Later I construct these objects to build a basic map. If you notice I do `box = ...` when constructing the objects.

If I don't define something with the constructor, the collision detection fails to work. Yet I have no idea why.

**Comment by ProximaNova** [comment]
Is this still a problem?

It'd be cool if userscripts worked on web browsers for tablets such as "Amazon Silk" and "Dolphin Browser".
